### ISSUE TITLE
12 - Buy macbook pro retina 15

### ISSUE THREAD

**Issue by solairerove** [solairerove/woodstock#12]
Travel with laptop through belarushka board.

**Comment by solairerove** [comment]
Step 1 - travel to poland DONE

**Comment by solairerove** [comment]
Step 2 -  buy mac DONE

**Comment by solairerove** [comment]
Step 3 - return to belarushka

**Comment by vlsidlyarevich** [comment]
Be careful, write some tests

**Comment by vlsidlyarevich** [comment]
Don't make yout mac public property

**Comment by solairerove** [comment]
Done ept
