### ISSUE TITLE
#7 - gradle

### ISSUE THREAD

**Issue by solairerove** [solairerove/woodstock#8]
see soho middleware gradle project with check styles

**Comment by billbarni** [comment]
Could you take a look at this repo and see if that you get interested in his gradle integration?
https://github.com/kucharzyk/kotlin-ng2-demo

The gradle integration that is achieved there is very good. The only problem is to convert the `build.gradle.kts` back to a 'pure' `build.gradle` file.

Sorry if this is not pertinent.

**Comment by solairerove** [comment]
I've never use kotlin, but I think there isn't any issues to you migrate to vanilla gradle
